<div class="col-3-1">
                      <div id="a1portalSkin_ctr109926109926_Column3C33A34A33_QHDCPM109926M1" class="qhd_column_contain"><!-- Start_Module_109934 --><a name="31976" id="31976"></a>
                        <div class="module-default">
                          <div class="module-inner">
                            <div id="a1portalSkin_ctr109926109926_Column3C33A34A33_ctr109934109934_mainArea" class="module-content"><!-- Start_Module_109934 -->
                              <div class="qhd-content">
                                <p style="text-align: center;"> <a href="[field:typeurl /]" target="_blank"><img alt="" src="/skin/img/97eb589b-607c-42b9-9cea-a975ab398f4f.jpg" style="width: 376px; height: 250px;" /></a></p>
                                <p style="text-align: center;"> <a href="[field:typeurl /]" target="_blank"><span style="font-size:20px;">Men Series</span></a></p>
                              </div>
                              <!-- End_Module_109934 --></div>
                          </div>
                        </div>
                      </div>
                    </div>