<div class="col-3-1">
                    <div id="a1portalSkin_ctr109927109927_Column3C33A34A33_QHDCPM109927M2" class="qhd_column_contain"><!-- Start_Module_109932 --><a name="31981" id="31981"></a>
                      <div class="module-default">
                        <div class="module-inner">
                          <div id="a1portalSkin_ctr109927109927_Column3C33A34A33_ctr109932109932_mainArea" class="module-content"><!-- Start_Module_109932 --><!-- S link-setion -->
                            <div class="link-setion"><a href="[field:typeurl /]" target="_blank">
                              <div class="link-img"><img src="/skin/img/fc969f62-12a7-46d9-a630-99fcc7779f51.jpg" alt="[field:typename /]" /></div>
                              <div class="link-name-default">
                                <h3>[field:typename /]</h3>
                              </div>
                              <div class="link-setion-text">
                                <div class="link-name">
                                  <h3>[field:typename /]</h3>
                                </div>
                                <div class="link-summary">
                                  <p>[field:description/]</p>
                                </div>
                                <span class="link-more">View Detail</span></div>
                              <div class="opacity-overlay"></div>
                              </a></div>
                            <!-- E link-setion --><!-- End_Module_109932 --></div>
                        </div>
                      </div>
                    </div>
                  </div>