<?php
$z[0]=Array("global","\n                      \$a=\"\n                      <li class='col-3-1 last not-animated' data-animate='fadeInUp'>\";\n                        \$b=\"\n                      \n                      <li class='col-3-1 not-animated' data-animate='fadeInUp'>\";\n                        if ((@me%3)==0 && @me!=24)  @me=\$a;\n                        else  @me=\$b;\n                        ",0,428);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",542,557);
$z[2]=Array("picname","",585,601);
$z[3]=Array("title","",608,622);
$z[4]=Array("arcurl","",734,749);
$z[5]=Array("title","",767,781);

?>