<?php
$z[0]=Array("field","",11,37);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",68,96);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",116,145);
$z[2][4]['name']="typename";
$z[3]=Array("sql","\r\n                    <li class=\"\"><a class=\"\" href=\"[field:typedir function=\"cn_substr(@me,200,9) \" /]\" target=\"\"><strong>[field:typename/]</strong></a></li>\r\n                    ",220,484);
$z[3][4]['sql']="Select * from `dede_arctype` where reid=~id~ ORDER BY id";

?>