<?php
$z[0]=Array("global","\n                      \$a=\"\n                      <li class='col-4-1 not-animated last' data-animate='fadeInUp'>\";\n                        \$b=\"\n                      \n                      <li class='col-4-1 not-animated' data-animate='fadeInUp'>\";\n                        if ((@me%3)==0 && @me!=24)  @me=\$a;\n                        else  @me=\$b;\n                        ",0,428);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",489,504);
$z[2]=Array("picname","",532,548);
$z[3]=Array("arcurl","",663,678);
$z[4]=Array("title","",696,710);

?>