<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/161030/1-161030162011.png ",93,240);
$z[1][4]['ddimg']="/uploads/allimg/161030/1-161030162011.png";
$z[1][4]['text']="";
$z[1][4]['width']="800";
$z[1][4]['height']="800";
$z[2]=Array("img"," /uploads/allimg/161030/1-161030162012.png ",242,389);
$z[2][4]['ddimg']="/uploads/allimg/161030/1-161030162012.png";
$z[2][4]['text']="";
$z[2][4]['width']="800";
$z[2][4]['height']="800";
$z[3]=Array("img"," /uploads/allimg/161030/1-161030162015.png ",391,538);
$z[3][4]['ddimg']="/uploads/allimg/161030/1-161030162015.png";
$z[3][4]['text']="";
$z[3][4]['width']="800";
$z[3][4]['height']="800";

?>