<?php
$z[0]=Array("global","\r\n                      \$a=\"\r\n                      <li class='col-3-1 last not-animated' data-animate='fadeInUp'>\";\r\n                        \$b=\"\r\n                      \r\n                      <li class='col-3-1 not-animated' data-animate='fadeInUp'>\";\r\n                        if ((@me%3)==0 && @me!=24)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        ",0,436);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",552,567);
$z[2]=Array("picname","",595,611);
$z[3]=Array("title","",618,632);
$z[4]=Array("arcurl","",746,761);
$z[5]=Array("title","",779,793);

?>