<div class="col-3-1">
                    <div id="a1portalSkin_ctr109927109927_Column3C33A34A33_QHDCPM109927M1" class="qhd_column_contain"><!-- Start_Module_109931 --><a name="31980" id="31980"></a>
                      <div class="module-default">
                        <div class="module-inner">
                          <div id="a1portalSkin_ctr109927109927_Column3C33A34A33_ctr109931109931_mainArea" class="module-content"><!-- Start_Module_109931 --><!-- S link-setion -->
                            <div class="link-setion"><a href="[field:typeurl /]" target="_blank">
                              <div class="link-img"><img src="/skin/img/cd9e332a-e38f-4717-a47f-fe2e1bb3f4f5.jpg" alt="[field:typename /]" /></div>
                              <div class="link-name-default">
                                <h3>[field:typename /]</h3>
                              </div>
                              <div class="link-setion-text">
                                <div class="link-name">
                                  <h3>[field:typename /]</h3>
                                </div>
                                <div class="link-summary">
                                  <p>[field:description/]</p>
                                </div>
                                <span class="link-more">View Detail</span></div>
                              <div class="opacity-overlay"></div>
                              </a></div>
                            <!-- E link-setion --><!-- End_Module_109931 --></div>
                        </div>
                      </div>
                    </div>
                  </div>