<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/161030/1-161030163A4.png ",93,239);
$z[1][4]['ddimg']="/uploads/allimg/161030/1-161030163A4.png";
$z[1][4]['text']="";
$z[1][4]['width']="1200";
$z[1][4]['height']="850";
$z[2]=Array("img"," /uploads/allimg/161030/1-161030163A6.png ",241,387);
$z[2][4]['ddimg']="/uploads/allimg/161030/1-161030163A6.png";
$z[2][4]['text']="";
$z[2][4]['width']="1200";
$z[2][4]['height']="850";
$z[3]=Array("img"," /uploads/allimg/161030/1-161030163A7.png ",389,535);
$z[3][4]['ddimg']="/uploads/allimg/161030/1-161030163A7.png";
$z[3][4]['text']="";
$z[3][4]['width']="1200";
$z[3][4]['height']="850";
$z[4]=Array("img"," /uploads/allimg/161030/1-161030163A8.png ",537,683);
$z[4][4]['ddimg']="/uploads/allimg/161030/1-161030163A8.png";
$z[4][4]['text']="";
$z[4][4]['width']="1200";
$z[4][4]['height']="850";
$z[5]=Array("img"," /uploads/allimg/161030/1-161030163F0.png ",685,831);
$z[5][4]['ddimg']="/uploads/allimg/161030/1-161030163F0.png";
$z[5][4]['text']="";
$z[5][4]['width']="1200";
$z[5][4]['height']="850";

?>