<?php
$z[0]=Array("global","\r\n                      \$a=\"\r\n                      <li class='col-4-1 not-animated last' data-animate='fadeInUp'>\";\r\n                        \$b=\"\r\n                      \r\n                      <li class='col-4-1 not-animated' data-animate='fadeInUp'>\";\r\n                        if ((@me%3)==0 && @me!=24)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        ",0,436);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",498,513);
$z[2]=Array("picname","",541,557);
$z[3]=Array("arcurl","",674,689);
$z[4]=Array("title","",707,721);

?>