<div class="col-3-1">
                      <div id="a1portalSkin_ctr109926109926_Column3C33A34A33_QHDCPM109926M2" class="qhd_column_contain"><!-- Start_Module_109935 --><a name="31977" id="31977"></a>
                        <div class="module-default">
                          <div class="module-inner">
                            <div id="a1portalSkin_ctr109926109926_Column3C33A34A33_ctr109935109935_mainArea" class="module-content"><!-- Start_Module_109935 -->
                              <div class="qhd-content">
                                <p style="text-align: center;"> <a href="[field:typeurl /]" target="_blank"><img alt="" src="/skin/img/6c7051e0-4615-448a-821f-a56f737f8943.jpg" /></a></p>
                                <p style="text-align: center;"> <a href="[field:typeurl /]" target="_blank"><span style="font-size:20px;">女士系列</span></a></p>
                              </div>
                              <!-- End_Module_109935 --></div>
                          </div>
                        </div>
                      </div>
                    </div>