<?php
$z[0]=Array("global","\n                      \$a=\"\n                      <li class='col-4-1 not-animated last' data-animate='fadeInUp'>\";\n                        \$b=\"\n                      \n                      <li class='col-4-1 not-animated' data-animate='fadeInUp'>\";\n                        if ((@me%3)==0 && @me!=24)  @me=\$a;\n                        else  @me=\$b;\n                        ",0,428);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",544,559);
$z[2]=Array("picname","",587,603);
$z[3]=Array("arcurl","",721,736);
$z[4]=Array("title","",754,768);
$z[5]=Array("description","",956,1006);
$z[5][4]['function']="cn_substr(@me,320)";

?>