<div class="col-3-1 last">
                    <div id="a1portalSkin_ctr109927109927_Column3C33A34A33_QHDCPM109927M3" class="qhd_column_contain"><!-- Start_Module_109933 --><a name="31982" id="31982"></a>
                      <div class="module-default">
                        <div class="module-inner">
                          <div id="a1portalSkin_ctr109927109927_Column3C33A34A33_ctr109933109933_mainArea" class="module-content"><!-- Start_Module_109933 --><!-- S link-setion -->
                            <div class="link-setion"><a href="[field:typeurl /]" target="_blank">
                              <div class="link-img"><img src="/skin/img/be77a4cf-11b9-4707-8820-e0cc611088b2.jpg" alt="[field:typename /]" /></div>
                              <div class="link-name-default">
                                <h3>[field:typename /]</h3>
                              </div>
                              <div class="link-setion-text">
                                <div class="link-name">
                                  <h3>[field:typename /]</h3>
                                </div>
                                <div class="link-summary">
                                  <p>[field:description/]</p>
                                </div>
                                <span class="link-more">View Detail</span></div>
                              <div class="opacity-overlay"></div>
                              </a></div>
                            <!-- E link-setion --><!-- End_Module_109933 --></div>
                        </div>
                      </div>
                    </div>
                  </div>