<?php
$z[0]=Array("field","",316,335);
$z[0][4]['name']="title";
$z[1]=Array("global","",336,362);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",402,431);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",470,528);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3257,3292);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",4162,4181);
$z[5][4]['name']="title";
$z[6]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",4296,4370);
$z[7]=Array("field","",4423,4475);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d',@me)";
$z[8]=Array("field","",5608,5626);
$z[8][4]['name']="body";
$z[9]=Array("include","",6004,6041);
$z[9][4]['filename']="footer.htm";

?>