<?php
$z[0]=Array("field","",316,335);
$z[0][4]['name']="title";
$z[1]=Array("global","",336,362);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",402,431);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",470,528);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3257,3292);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",4192,4211);
$z[5][4]['name']="title";
$z[6]=Array("productimagelist","\n                        <li><img src=\"[field:imgsrc/]\" data-large-src=\"[field:imgsrc/]\" alt=\"[field:text/]\" /></li>\n                        ",4395,4583);
$z[7]=Array("include","",5188,5225);
$z[7][4]['filename']="footer.htm";

?>