<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/161030/1-161030162R3.png ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/161030/1-161030162R3.png";
$z[1][4]['text']="";
$z[1][4]['width']="800";
$z[1][4]['height']="800";
$z[2]=Array("img"," /uploads/allimg/161030/1-161030162R5.png ",240,385);
$z[2][4]['ddimg']="/uploads/allimg/161030/1-161030162R5.png";
$z[2][4]['text']="";
$z[2][4]['width']="800";
$z[2][4]['height']="800";

?>