<div class="col-3-1 last">
                      <div id="a1portalSkin_ctr109926109926_Column3C33A34A33_QHDCPM109926M3" class="qhd_column_contain"><!-- Start_Module_109936 --><a name="31978" id="31978"></a>
                        <div class="module-default">
                          <div class="module-inner">
                            <div id="a1portalSkin_ctr109926109926_Column3C33A34A33_ctr109936109936_mainArea" class="module-content"><!-- Start_Module_109936 -->
                              <div class="qhd-content">
                                <p style="text-align: center;"> <a href="[field:typeurl /]" target="_blank"><img alt="" src="/skin/img/2db9ef17-8a31-48c6-8a47-6b80a5ad321b.jpg" /></a></p>
                                <p style="text-align: center;"> <a href="[field:typeurl /]" target="_blank"><span style="font-size:20px;">FEDEX联邦快递</span></a></p>
                              </div>
                              <!-- End_Module_109936 --></div>
                          </div>
                        </div>
                      </div>
                    </div>