<?php
$z[0]=Array("global","\r\n                      \$a=\"\r\n                      <li class='col-4-1 not-animated last' data-animate='fadeInUp'>\";\r\n                        \$b=\"\r\n                      \r\n                      <li class='col-4-1 not-animated' data-animate='fadeInUp'>\";\r\n                        if ((@me%3)==0 && @me!=24)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        ",0,436);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",554,569);
$z[2]=Array("picname","",597,613);
$z[3]=Array("arcurl","",733,748);
$z[4]=Array("title","",766,780);
$z[5]=Array("description","",972,1022);
$z[5][4]['function']="cn_substr(@me,320)";

?>