<?php
$z[0]=Array("field","",335,354);
$z[0][4]['name']="title";
$z[1]=Array("global","",355,381);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",422,451);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",491,549);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3301,3339);
$z[4][4]['filename']="en_head.htm";
$z[5]=Array("arclist","\r\n                <div class=\"carousel-item\">\r\n                  <div class=\"carousel-img\"><a href=\"javascript:;\" target=\"\"><img src=\"[field:picname/]\" height=\"500\" alt=\"[field:title/]\" /></a></div>\r\n                </div>\r\n                ",3869,4161);
$z[5][4]['typeid']="46";
$z[5][4]['row']="4";
$z[6]=Array("field","",5238,5267);
$z[6][4]['name']="position";
$z[7]=Array("type","<h2>[field:typename /]</h2>",5393,5443);
$z[8]=Array("productimagelist","\r\n                            <li><a href=\"[field:imgsrc/]\"><img src=\"[field:imgsrc/]\" width=\"85\" height=\"85\" data-large-src=\"[field:imgsrc/]\" alt=\"[field:text/]\" /></a></li>\r\n                        ",6385,6632);
$z[9]=Array("field","",7536,7555);
$z[9][4]['name']="title";
$z[10]=Array("field","",7830,7848);
$z[10][4]['name']="zsml";
$z[11]=Array("field","",7893,7911);
$z[11][4]['name']="ydxm";
$z[12]=Array("field","",7956,7972);
$z[12][4]['name']="ys";
$z[13]=Array("field","",9733,9751);
$z[13][4]['name']="body";
$z[14]=Array("include","",10072,10107);
$z[14][4]['filename']="left.htm";
$z[15]=Array("include","",10214,10254);
$z[15][4]['filename']="en_footer.htm";

?>