<?php
$z[0]=Array("field","",322,341);
$z[0][4]['name']="title";
$z[1]=Array("global","",342,368);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",409,438);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",478,536);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3297,3335);
$z[4][4]['filename']="en_head.htm";
$z[5]=Array("field","",4247,4266);
$z[5][4]['name']="title";
$z[6]=Array("productimagelist","\r\n                        <li><img src=\"[field:imgsrc/]\" data-large-src=\"[field:imgsrc/]\" alt=\"[field:text/]\" /></li>\r\n                        ",4454,4644);
$z[7]=Array("include","",5265,5305);
$z[7][4]['filename']="en_footer.htm";

?>