<?php
$z[0]=Array("field","",322,341);
$z[0][4]['name']="title";
$z[1]=Array("global","",342,368);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",409,438);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",478,536);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3297,3335);
$z[4][4]['filename']="en_head.htm";
$z[5]=Array("field","",4217,4236);
$z[5][4]['name']="title";
$z[6]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",4349,4423);
$z[7]=Array("field","",4477,4529);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d',@me)";
$z[8]=Array("field","",5669,5687);
$z[8][4]['name']="body";
$z[9]=Array("include","",6077,6117);
$z[9][4]['filename']="en_footer.htm";

?>