<?php
$z[0]=Array("field","",329,348);
$z[0][4]['name']="title";
$z[1]=Array("global","",349,375);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",415,444);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",483,541);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3262,3300);
$z[4][4]['filename']="en_head.htm";
$z[5]=Array("arclist","\n                <div class=\"carousel-item\">\n                  <div class=\"carousel-img\"><a href=\"javascript:;\" target=\"\"><img src=\"[field:picname/]\" height=\"500\" alt=\"[field:title/]\" /></a></div>\n                </div>\n                ",3823,4111);
$z[5][4]['typeid']="46";
$z[5][4]['row']="4";
$z[6]=Array("field","",5164,5193);
$z[6][4]['name']="position";
$z[7]=Array("type","<h2>[field:typename /]</h2>",5316,5366);
$z[8]=Array("productimagelist","\n                            <li><a href=\"[field:imgsrc/]\"><img src=\"[field:imgsrc/]\" width=\"85\" height=\"85\" data-large-src=\"[field:imgsrc/]\" alt=\"[field:text/]\" /></a></li>\n                        ",6295,6540);
$z[9]=Array("field","",7423,7442);
$z[9][4]['name']="title";
$z[10]=Array("field","",7711,7729);
$z[10][4]['name']="zsml";
$z[11]=Array("field","",7773,7791);
$z[11][4]['name']="ydxm";
$z[12]=Array("field","",7835,7851);
$z[12][4]['name']="ys";
$z[13]=Array("field","",9592,9610);
$z[13][4]['name']="body";
$z[14]=Array("include","",9921,9956);
$z[14][4]['filename']="left.htm";
$z[15]=Array("include","",10060,10100);
$z[15][4]['filename']="en_footer.htm";

?>