<?php
$z[0]=Array("channelartlist","\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\n                                 ",1481,1720);
$z[0][4]['typeid']="25,26,27,32,0";
$z[1]=Array("channelartlist","\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\n                                 ",2947,3183);
$z[1][4]['typeid']="34,35,36,0";
$z[2]=Array("channelartlist","\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\n                                 ",4414,4650);
$z[2][4]['typeid']="29,30,31,0";
$z[3]=Array("channelartlist","\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\n                                 ",5877,6116);
$z[3][4]['typeid']="40,41,42,43,0";
$z[4]=Array("global","",8678,8706);
$z[4][4]['name']="cfg_powerbyen";
$z[5]=Array("global","",8724,8750);
$z[5][4]['name']="cfg_beianen";

?>