<?php
$z[0]=Array("channelartlist","\r\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\r\n                                 ",1502,1743);
$z[0][4]['typeid']="25,26,27,32,0";
$z[1]=Array("channelartlist","\r\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\r\n                                 ",2990,3228);
$z[1][4]['typeid']="34,35,36,0";
$z[2]=Array("channelartlist","\r\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\r\n                                 ",4479,4717);
$z[2][4]['typeid']="29,30,31,0";
$z[3]=Array("channelartlist","\r\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\r\n                                 ",5964,6205);
$z[3][4]['typeid']="40,41,42,43,0";
$z[4]=Array("global","",8811,8839);
$z[4][4]['name']="cfg_powerbyen";
$z[5]=Array("global","",8857,8883);
$z[5][4]['name']="cfg_beianen";

?>