<?php
$z[0]=Array("global","",314,340);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",3299,3337);
$z[1][4]['filename']="en_head.htm";
$z[2]=Array("field","",3941,3970);
$z[2][4]['name']="position";
$z[3]=Array("type","<h2>[field:typename /]</h2>",4093,4143);
$z[4]=Array("field","",4626,4654);
$z[4][4]['name']="content";
$z[5]=Array("include","",4860,4896);
$z[5][4]['filename']="left1.htm";
$z[6]=Array("include","",5006,5046);
$z[6][4]['filename']="en_footer.htm";

?>