<?php
$z[0]=Array("global","",316,342);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",382,411);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",450,480);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",3209,3247);
$z[3][4]['filename']="en_head.htm";
$z[4]=Array("field","",4027,4055);
$z[4][4]['name']="content";
$z[5]=Array("include","",8790,8830);
$z[5][4]['filename']="en_footer.htm";

?>