<?php
$z[0]=Array("global","",322,348);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",389,418);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",458,488);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",3249,3287);
$z[3][4]['filename']="en_head.htm";
$z[4]=Array("field","",4078,4106);
$z[4][4]['name']="content";
$z[5]=Array("include","",8958,8998);
$z[5][4]['filename']="en_footer.htm";

?>