<?php
$z[0]=Array("global","",319,345);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",3341,3379);
$z[1][4]['filename']="en_head.htm";
$z[2]=Array("field","",3990,4019);
$z[2][4]['name']="position";
$z[3]=Array("type","<h2>[field:typename /]</h2>",4145,4195);
$z[4]=Array("field","",4687,4715);
$z[4][4]['name']="content";
$z[5]=Array("include","",4929,4965);
$z[5][4]['filename']="left1.htm";
$z[6]=Array("include","",5078,5118);
$z[6][4]['filename']="en_footer.htm";

?>