<?php
$z[0]=Array("global","",319,345);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",3341,3379);
$z[1][4]['filename']="en_head.htm";
$z[2]=Array("field","",3990,4019);
$z[2][4]['name']="position";
$z[3]=Array("type","<h2>[field:typename /]</h2>",4145,4195);
$z[4]=Array("field","",4687,4715);
$z[4][4]['name']="content";
$z[5]=Array("field","",5114,5172);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("type"," <li class=\"current\"><a href=\"[field:typelink/]\" target=\"\">[field:typename/]</a></li>",5330,5438);
$z[7]=Array("include","",6444,6484);
$z[7][4]['filename']="en_footer.htm";

?>