<?php
$z[0]=Array("global","",322,348);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",389,418);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",458,488);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",3249,3287);
$z[3][4]['filename']="en_head.htm";
$z[4]=Array("include","",3579,3613);
$z[4][4]['filename']="top.htm";
$z[5]=Array("field","",4127,4155);
$z[5][4]['name']="content";
$z[6]=Array("include","",4432,4472);
$z[6][4]['filename']="en_footer.htm";

?>