<?php
$z[0]=Array("global","",314,340);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",3299,3337);
$z[1][4]['filename']="en_head.htm";
$z[2]=Array("field","",3941,3970);
$z[2][4]['name']="position";
$z[3]=Array("type","<h2>[field:typename /]</h2>",4093,4143);
$z[4]=Array("field","",4626,4654);
$z[4][4]['name']="content";
$z[5]=Array("field","",5042,5100);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("type"," <li class=\"current\"><a href=\"[field:typelink/]\" target=\"\">[field:typename/]</a></li>",5253,5361);
$z[7]=Array("include","",6343,6383);
$z[7][4]['filename']="en_footer.htm";

?>