<?php
$z[0]=Array("channelartlist","\r\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\r\n                                 ",1507,1745);
$z[0][4]['typeid']="3,4,5,10,0";
$z[1]=Array("channelartlist","\r\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\r\n                                 ",3000,3238);
$z[1][4]['typeid']="12,13,14,0";
$z[2]=Array("channelartlist","\r\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\r\n                                 ",4493,4728);
$z[2][4]['typeid']="7,8,9,0";
$z[3]=Array("channelartlist","\r\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\r\n                                 ",5983,6224);
$z[3][4]['typeid']="18,19,20,21,0";
$z[4]=Array("global","",8831,8857);
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",8875,8899);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("flink"," [field:link /] ",9118,9183);
$z[6][4]['type']="textall";
$z[6][4]['row']="24";

?>