<?php
$z[0]=Array("channelartlist","\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\n                                 ",1486,1722);
$z[0][4]['typeid']="3,4,5,10,0";
$z[1]=Array("channelartlist","\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\n                                 ",2957,3193);
$z[1][4]['typeid']="12,13,14,0";
$z[2]=Array("channelartlist","\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\n                                 ",4428,4661);
$z[2][4]['typeid']="7,8,9,0";
$z[3]=Array("channelartlist","\n                                  <li><a href=\"{dede:field name='typeurl'/}\" target=\"\"><span>{dede:field name='typename'/}</span></a></li>\n                                 ",5896,6135);
$z[3][4]['typeid']="18,19,20,21,0";
$z[4]=Array("global","",8698,8724);
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",8742,8766);
$z[5][4]['name']="cfg_beian";
$z[6]=Array("flink"," [field:link /] ",8984,9049);
$z[6][4]['type']="textall";
$z[6][4]['row']="24";

?>