<?php
$z[0]=Array("global","",314,340);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",3299,3334);
$z[1][4]['filename']="head.htm";
$z[2]=Array("field","",3942,3971);
$z[2][4]['name']="position";
$z[3]=Array("type","<h2>[field:typename /]</h2>",4094,4144);
$z[4]=Array("field","",4627,4655);
$z[4][4]['name']="content";
$z[5]=Array("include","",4861,4897);
$z[5][4]['filename']="left1.htm";
$z[6]=Array("include","",5007,5044);
$z[6][4]['filename']="footer.htm";

?>