<?php
$z[0]=Array("global","",322,348);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",389,418);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",458,488);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",3249,3284);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",4075,4103);
$z[4][4]['name']="content";
$z[5]=Array("include","",8958,8995);
$z[5][4]['filename']="footer.htm";

?>