<?php
$z[0]=Array("global","",319,345);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",3341,3376);
$z[1][4]['filename']="head.htm";
$z[2]=Array("field","",3991,4020);
$z[2][4]['name']="position";
$z[3]=Array("type","<h2>[field:typename /]</h2>",4146,4196);
$z[4]=Array("field","",4688,4716);
$z[4][4]['name']="content";
$z[5]=Array("include","",4930,4966);
$z[5][4]['filename']="left1.htm";
$z[6]=Array("include","",5079,5116);
$z[6][4]['filename']="footer.htm";

?>