<?php
$z[0]=Array("global","",316,342);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",382,411);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",450,480);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",3209,3244);
$z[3][4]['filename']="head.htm";
$z[4]=Array("include","",3532,3566);
$z[4][4]['filename']="top.htm";
$z[5]=Array("field","",4072,4100);
$z[5][4]['name']="content";
$z[6]=Array("include","",4368,4405);
$z[6][4]['filename']="footer.htm";

?>