<?php  exit();
/*
Page: /index.php?upcache=1
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '16,0) AND ispart<>2 AND ishidden<>1  ORDER BY sortrank ASC LIMIT 20' at line 2 <br />Error sql: <font color='red'>SELECT id,typename,typedir,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                                            FROM `dede_arctype` WHERE  id IN(23,5,,16,0) AND ispart<>2 AND ishidden<>1  ORDER BY sortrank ASC LIMIT 20</font>
Time2016-10-05 13:27:59
*/
?>
